# 02 — Silver Cleaning & Data Quality

Bronze JSONL → audited Silver Parquet + DQ reports. **No Gold target. No modeling.**

- Event absence ≠ missing data (e.g. no pit rows → handled in Gold).
- Outliers flagged; only domain-invalid values removed.
- Run after Bronze with the **same** `USE_GOOGLE_DRIVE` setting as notebook 01.

## Colab setup (required every session)

Identical to `00` and `01`: clone, `pip install -e .`, Drive mount, then import `openf1_pipeline`.

In [1]:
import os
import subprocess
import sys
from pathlib import Path

# A. Repository (code)
REPO_URL = "https://github.com/dk546/openf1-big-data-pipeline.git"
REPO_NAME = "openf1-big-data-pipeline"
PROJECT_ROOT = Path(f"/content/{REPO_NAME}")

# B. Google Drive persistence (outputs) — set OPENF1_DATA_ROOT before importing config
USE_GOOGLE_DRIVE = True
DRIVE_OUTPUT_ROOT = Path("/content/drive/MyDrive/openf1_big_data_pipeline")

if USE_GOOGLE_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    DRIVE_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    os.environ["OPENF1_DATA_ROOT"] = str(DRIVE_OUTPUT_ROOT)
    print("OPENF1_DATA_ROOT:", os.environ["OPENF1_DATA_ROOT"])
else:
    os.environ.pop("OPENF1_DATA_ROOT", None)
    print("OPENF1_DATA_ROOT not set — repo-local outputs.")

# D. Clone or update repository
if not PROJECT_ROOT.exists():
    print("Cloning repository...")
    subprocess.run(["git", "clone", REPO_URL, str(PROJECT_ROOT)], check=True)
else:
    print("Updating repository...")
    subprocess.run(["git", "-C", str(PROJECT_ROOT), "pull"], check=False)

os.chdir(PROJECT_ROOT)
print("Working directory:", Path.cwd())

# E. Verify project files
_checks = {
    "README.md": PROJECT_ROOT / "README.md",
    "pyproject.toml": PROJECT_ROOT / "pyproject.toml",
    "src/openf1_pipeline": PROJECT_ROOT / "src" / "openf1_pipeline",
    "src/openf1_pipeline/__init__.py": PROJECT_ROOT / "src" / "openf1_pipeline" / "__init__.py",
    "src/openf1_pipeline/config.py": PROJECT_ROOT / "src" / "openf1_pipeline" / "config.py",
}
for name, path in _checks.items():
    if not path.exists():
        raise FileNotFoundError(f"Missing {name}: {path}")

# F. Install dependencies and editable package
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", "."], check=True)

# G. Fallback: src on sys.path
_src = PROJECT_ROOT / "src"
if str(_src) not in sys.path:
    sys.path.insert(0, str(_src))

# H. Import test
import openf1_pipeline  # noqa: E402

from openf1_pipeline.config import (  # noqa: E402
    ensure_project_directories,
    get_artifacts_dir,
    get_bronze_dir,
    get_data_dir,
    get_gold_dir,
    get_output_root,
    get_project_root,
    get_reports_dir,
    get_silver_dir,
)

paths = ensure_project_directories()

# I. Path summary
print("PROJECT_ROOT:", get_project_root())
print("OUTPUT_ROOT:", get_output_root())
print("DATA_DIR:", get_data_dir())
print("BRONZE_DIR:", get_bronze_dir())
print("SILVER_DIR:", get_silver_dir())
print("GOLD_DIR:", get_gold_dir())
print("REPORTS_DIR:", get_reports_dir())
print("ARTIFACTS_DIR:", get_artifacts_dir())

Mounted at /content/drive
OPENF1_DATA_ROOT: /content/drive/MyDrive/openf1_big_data_pipeline
Cloning repository...
Working directory: /content/openf1-big-data-pipeline
PROJECT_ROOT: /content/openf1-big-data-pipeline
OUTPUT_ROOT: /content/drive/MyDrive/openf1_big_data_pipeline
DATA_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data
BRONZE_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data/bronze
SILVER_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data/silver
GOLD_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data/gold
REPORTS_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/reports
ARTIFACTS_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/artifacts

## Bronze prerequisites

In [2]:
from pathlib import Path

from openf1_pipeline.config import (
    get_bronze_dir,
    get_data_quality_reports_dir,
    get_manifests_dir,
    get_output_root,
    get_silver_dir,
)
from openf1_pipeline.silver.build_silver import run_silver_cleaning

BRONZE_DIR = get_bronze_dir()
SILVER_DIR = get_silver_dir()
DATA_QUALITY_REPORTS_DIR = get_data_quality_reports_dir()
MANIFESTS_DIR = get_manifests_dir()

print("OUTPUT_ROOT:", get_output_root())
print("BRONZE_DIR:", BRONZE_DIR)
print("SILVER_DIR:", SILVER_DIR)
print("DATA_QUALITY_REPORTS_DIR:", DATA_QUALITY_REPORTS_DIR)

jsonl_files = list(BRONZE_DIR.rglob("*.jsonl")) if BRONZE_DIR.is_dir() else []
manifest_path = MANIFESTS_DIR / "ingestion_manifest.csv"
row_counts_path = DATA_QUALITY_REPORTS_DIR / "bronze_row_counts.csv"

print(f"Bronze JSONL files found: {len(jsonl_files)}")
print("ingestion_manifest.csv:", manifest_path.exists(), manifest_path)
print("bronze_row_counts.csv:", row_counts_path.exists(), row_counts_path)

if not jsonl_files:
    raise FileNotFoundError(
        f"Bronze data not found at {BRONZE_DIR}. "
        "Run 01_ingestion_bronze.ipynb first with the same USE_GOOGLE_DRIVE setting."
    )

OUTPUT_ROOT: /content/drive/MyDrive/openf1_big_data_pipeline
BRONZE_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data/bronze
SILVER_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/data/silver
DATA_QUALITY_REPORTS_DIR: /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality
Bronze JSONL files found: 16
ingestion_manifest.csv: True /content/drive/MyDrive/openf1_big_data_pipeline/artifacts/manifests/ingestion_manifest.csv
bronze_row_counts.csv: True /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/bronze_row_counts.csv

## Run Silver cleaning

In [3]:
outputs = run_silver_cleaning(
    bronze_dir=BRONZE_DIR,
    silver_dir=SILVER_DIR,
    data_quality_reports_dir=DATA_QUALITY_REPORTS_DIR,
)
outputs["summary"]

INFO:openf1_pipeline.silver.build_silver:Loaded Bronze meetings: 25 rows from 1 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze sessions: 123 rows from 1 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze drivers: 40 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze laps: 2031 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze pit: 62 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze weather: 303 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze position: 927 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze race_control: 139 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze session_result: 40 rows from 2 files
INFO:openf1_pipeline.silver.build_silver:Loaded Bronze starting_grid: 0 rows from 0 files
INFO:openf1_pipeline.quality.duplicates:Skipped key duplicate check for starting_grid: missing columns ['session_key', 'driver_number']
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/meetings_clean.parquet (25 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver meetings -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/meetings_clean.parquet (25 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/sessions_clean.parquet (123 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver sessions -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/sessions_clean.parquet (123 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/drivers_clean.parquet (40 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver drivers -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/drivers_clean.parquet (40 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/laps_clean.parquet (2031 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver laps -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/laps_clean.parquet (2031 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/pit_clean.parquet (62 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver pit -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/pit_clean.parquet (62 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/weather_clean.parquet (303 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver weather -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/weather_clean.parquet (303 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/position_clean.parquet (927 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver position -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/position_clean.parquet (927 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/race_control_clean.parquet (139 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver race_control -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/race_control_clean.parquet (139 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/session_result_clean.parquet (40 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver session_result -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/session_result_clean.parquet (40 rows)
INFO:openf1_pipeline.utils.io:Wrote Parquet /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/starting_grid_clean.parquet (0 rows)
INFO:openf1_pipeline.silver.build_silver:Saved Silver starting_grid -> /content/drive/MyDrive/openf1_big_data_pipeline/data/silver/starting_grid_clean.parquet (0 rows)
INFO:openf1_pipeline.quality.duplicates:Skipped key duplicate check for starting_grid: missing columns ['session_key', 'driver_number']
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_table_inventory.csv (10 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_missingness_before.csv (140 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_missingness_after.csv (140 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_duplicate_report.csv (40 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_outlier_report.csv (28 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_temporal_anomaly_report.csv (26 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_referential_integrity_report.csv (26 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_cleaning_rules.csv (10 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_cleaning_impact_summary.csv (10 rows)
INFO:openf1_pipeline.utils.io:Wrote CSV /content/drive/MyDrive/openf1_big_data_pipeline/reports/data_quality/silver_rejected_records_summary.csv (0 rows)
INFO:openf1_pipeline.silver.build_silver:Silver cleaning complete: {'tables_loaded': 10, 'total_rows_before': 3690, 'total_rows_after': 3690, 'total_rows_removed': 0, 'cleaning_rules_applied': 10, 'session_result_rows_after': 40}

{'tables_loaded': 10,
 'total_rows_before': 3690,
 'total_rows_after': 3690,
 'total_rows_removed': 0,
 'cleaning_rules_applied': 10,
 'session_result_rows_after': 40}

## Inspect cleaning impact

In [4]:
import pandas as pd

impact = pd.read_csv(outputs["paths"]["silver_cleaning_impact_summary"])
inventory = pd.read_csv(outputs["paths"]["silver_table_inventory"])
rules = pd.read_csv(outputs["paths"]["silver_cleaning_rules"])

display(inventory)
display(impact[["table_name", "rows_before", "rows_after", "rows_removed", "row_removal_pct"]])
display(rules.head(20))

,table_name,row_count,column_count,duplicate_full_rows,total_missing_cells,total_cells,missing_cell_pct
0,meetings,25,21,0,0,525,0.0000
1,sessions,123,18,0,0,2214,0.0000
2,drivers,40,16,0,1,640,0.1562
3,laps,2031,20,0,725,40620,1.7848
4,pit,62,12,0,62,744,8.3333
5,weather,303,14,0,0,4242,0.0000
6,position,927,9,0,0,8343,0.0000
7,race_control,139,15,0,534,2085,25.6115
8,session_result,40,15,0,22,600,3.6667
9,starting_grid,0,0,0,0,0,0.0000

       table_name  rows_before  rows_after  rows_removed  row_removal_pct
0        meetings           25          25             0              0.0
1        sessions          123         123             0              0.0
2         drivers           40          40             0              0.0
3            laps         2031        2031             0              0.0
4             pit           62          62             0              0.0
5         weather          303         303             0              0.0
6        position          927         927             0              0.0
7    race_control          139         139             0              0.0
8  session_result           40          40             0              0.0
9   starting_grid            0           0             0              0.0

,table_name,rule_id,rule_description,rows_before,rows_after,rows_removed,values_imputed,columns_affected,severity,rationale
0,meetings,SIL_NULL_MEETING_KEY,Drop rows with null keys: ['meeting_key'],25,25,0,0,meeting_key,high,meeting_key is required for calendar joins
1,sessions,SIL_NULL_SESSION_KEY,Drop rows with null keys: ['session_key'],123,123,0,0,session_key,high,session_key is the primary join key for all se...
2,drivers,SIL_NULL_DRIVER_KEYS,"Drop rows with null keys: ['session_key', 'dri...",40,40,0,0,"session_key,driver_number",high,session_key and driver_number required for dri...
3,laps,SIL_NULL_LAP_KEYS,"Drop rows with null keys: ['session_key', 'dri...",2031,2031,0,0,"session_key,driver_number,lap_number",high,"Lap grain requires session, driver, and lap nu..."
4,pit,SIL_NULL_PIT_KEYS,"Drop rows with null keys: ['session_key', 'dri...",62,62,0,0,"session_key,driver_number",high,Pit rows require session and driver
5,weather,SIL_NULL_WEATHER_SESSION,Drop rows with null keys: ['session_key'],303,303,0,0,session_key,high,Weather rows must link to a session
6,position,SIL_NULL_POSITION_KEYS,"Drop rows with null keys: ['session_key', 'dri...",927,927,0,0,"session_key,driver_number",high,Position updates require session and driver
7,race_control,SIL_NULL_RC_SESSION,Drop rows with null keys: ['session_key'],139,139,0,0,session_key,high,Race control messages must link to a session
8,session_result,SIL_NULL_RESULT_KEYS,"Drop rows with null keys: ['session_key', 'dri...",40,40,0,0,"session_key,driver_number",high,Final classification requires session and driver
9,starting_grid,SIL_EMPTY,No Bronze starting_grid data,0,0,0,0,NaN,low,Optional endpoint; heuristic may use sessions/...

## Missingness before vs after

In [5]:
miss_before = pd.read_csv(outputs["paths"]["silver_missingness_before"])
miss_after = pd.read_csv(outputs["paths"]["silver_missingness_after"])

display(miss_before.sort_values("missing_pct", ascending=False).groupby("table_name").head(5))
display(miss_after.sort_values("missing_pct", ascending=False).groupby("table_name").head(5))

,table_name,column_name,dtype,row_count,missing_count,missing_pct,non_missing_count,unique_count
79,pit,stop_duration,object,62,62,100.0000,0,0
119,race_control,qualifying_phase,object,139,139,100.0000,0,0
118,race_control,sector,float64,139,126,90.6475,13,4
113,race_control,driver_number,float64,139,101,72.6619,38,11
117,race_control,scope,object,139,84,60.4317,55,3
116,race_control,flag,object,139,84,60.4317,55,7
132,session_result,duration,float64,40,18,45.0000,22,22
63,laps,i1_speed,float64,2031,537,26.4402,1494,84
70,laps,st_speed,float64,2031,172,8.4687,1859,127
125,session_result,position,float64,40,2,5.0000,38,20
133,session_result,gap_to_leader,object,40,2,5.0000,38,23
49,drivers,headshot_url,object,40,1,2.5000,39,20
60,laps,duration_sector_1,float64,2031,7,0.3447,2024,1558
66,laps,lap_duration,float64,2031,2,0.0985,2029,1797
62,laps,duration_sector_3,float64,2031,2,0.0985,2029,1422
3,meetings,location,object,25,0,0.0000,25,24
2,meetings,meeting_official_name,object,25,0,0.0000,25,25
1,meetings,meeting_name,object,25,0,0.0000,25,25
0,meetings,meeting_key,int64,25,0,0.0000,25,25
7,meetings,country_flag,object,25,0,0.0000,25,21
32,sessions,location,object,123,0,0.0000,123,24
31,sessions,country_name,object,123,0,0.0000,123,21
28,sessions,circuit_short_name,object,123,0,0.0000,123,24
29,sessions,country_key,int64,123,0,0.0000,123,21
30,sessions,country_code,object,123,0,0.0000,123,21
43,drivers,full_name,object,40,0,0.0000,40,21
42,drivers,broadcast_name,object,40,0,0.0000,40,21
41,drivers,driver_number,int64,40,0,0.0000,40,21
40,drivers,session_key,int64,40,0,0.0000,40,2
75,pit,date,object,62,0,0.0000,62,61
76,pit,session_key,int64,62,0,0.0000,62,2
77,pit,lap_number,int64,62,0,0.0000,62,24
78,pit,lane_duration,float64,62,0,0.0000,62,38
92,weather,wind_direction,int64,303,0,0.0000,303,144
93,weather,meeting_key,int64,303,0,0.0000,303,2
94,weather,rainfall,int64,303,0,0.0000,303,1
95,weather,wind_speed,float64,303,0,0.0000,303,25
96,weather,track_temperature,float64,303,0,0.0000,303,75
107,position,source_endpoint,object,927,0,0.0000,927,1
106,position,source_file,object,927,0,0.0000,927,2
105,position,meeting_key,int64,927,0,0.0000,927,2
104,position,position,int64,927,0,0.0000,927,20
103,position,driver_number,int64,927,0,0.0000,927,21
128,session_result,points,float64,40,0,0.0000,40,13
129,session_result,dnf,bool,40,0,0.0000,40,2

,table_name,column_name,dtype,row_count,missing_count,missing_pct,non_missing_count,unique_count
79,pit,stop_duration,object,62,62,100.0000,0,0
119,race_control,qualifying_phase,object,139,139,100.0000,0,0
118,race_control,sector,float64,139,126,90.6475,13,4
113,race_control,driver_number,float64,139,101,72.6619,38,11
117,race_control,scope,object,139,84,60.4317,55,3
116,race_control,flag,object,139,84,60.4317,55,7
132,session_result,duration,float64,40,18,45.0000,22,22
63,laps,i1_speed,float64,2031,537,26.4402,1494,84
70,laps,st_speed,float64,2031,172,8.4687,1859,127
125,session_result,position,float64,40,2,5.0000,38,20
133,session_result,gap_to_leader,object,40,2,5.0000,38,23
49,drivers,headshot_url,object,40,1,2.5000,39,20
60,laps,duration_sector_1,float64,2031,7,0.3447,2024,1558
101,position,date,"datetime64[ns, UTC]",927,2,0.2157,925,352
66,laps,lap_duration,float64,2031,2,0.0985,2029,1797
62,laps,duration_sector_3,float64,2031,2,0.0985,2029,1422
0,meetings,meeting_key,int64,25,0,0.0000,25,25
3,meetings,location,object,25,0,0.0000,25,24
2,meetings,meeting_official_name,object,25,0,0.0000,25,25
1,meetings,meeting_name,object,25,0,0.0000,25,25
4,meetings,country_key,int64,25,0,0.0000,25,21
28,sessions,circuit_short_name,object,123,0,0.0000,123,24
29,sessions,country_key,int64,123,0,0.0000,123,21
30,sessions,country_code,object,123,0,0.0000,123,21
31,sessions,country_name,object,123,0,0.0000,123,21
43,drivers,full_name,object,40,0,0.0000,40,21
42,drivers,broadcast_name,object,40,0,0.0000,40,21
41,drivers,driver_number,int64,40,0,0.0000,40,21
40,drivers,session_key,int64,40,0,0.0000,40,2
38,sessions,source_year,int64,123,0,0.0000,123,1
75,pit,date,"datetime64[ns, UTC]",62,0,0.0000,62,61
77,pit,lap_number,int64,62,0,0.0000,62,24
80,pit,pit_duration,float64,62,0,0.0000,62,38
81,pit,meeting_key,int64,62,0,0.0000,62,2
91,weather,humidity,float64,303,0,0.0000,303,18
92,weather,wind_direction,int64,303,0,0.0000,303,144
94,weather,rainfall,int64,303,0,0.0000,303,1
93,weather,meeting_key,int64,303,0,0.0000,303,2
96,weather,track_temperature,float64,303,0,0.0000,303,75
107,position,source_endpoint,object,927,0,0.0000,927,1
106,position,source_file,object,927,0,0.0000,927,2
105,position,meeting_key,int64,927,0,0.0000,927,2
104,position,position,int64,927,0,0.0000,927,20
128,session_result,points,float64,40,0,0.0000,40,13
129,session_result,dnf,bool,40,0,0.0000,40,2

## Duplicates & referential integrity

In [6]:
dups = pd.read_csv(outputs["paths"]["silver_duplicate_report"])
ref = pd.read_csv(outputs["paths"]["silver_referential_integrity_report"])
rejected = pd.read_csv(outputs["paths"]["silver_rejected_records_summary"])

display(dups)
display(ref)
display(rejected)

,table_name,duplicate_type,duplicate_count,duplicate_pct,stage,key_columns,duplicate_key_count,affected_rows,affected_rows_pct,status
0,meetings,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
1,meetings,key_duplicate,NaN,NaN,before,meeting_key,0.0,0.0,0.0,checked
2,sessions,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
3,sessions,key_duplicate,NaN,NaN,before,session_key,0.0,0.0,0.0,checked
4,drivers,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
5,drivers,key_duplicate,NaN,NaN,before,"session_key,driver_number",0.0,0.0,0.0,checked
6,laps,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
7,laps,key_duplicate,NaN,NaN,before,"session_key,driver_number,lap_number",0.0,0.0,0.0,checked
8,pit,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
9,pit,key_duplicate,NaN,NaN,before,"session_key,driver_number,lap_number",0.0,0.0,0.0,checked
10,weather,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
11,weather,key_duplicate,NaN,NaN,before,"session_key,date",0.0,0.0,0.0,checked
12,position,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
13,position,key_duplicate,NaN,NaN,before,"session_key,driver_number,date",0.0,0.0,0.0,checked
14,race_control,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
15,race_control,key_duplicate,NaN,NaN,before,"session_key,date,message",0.0,0.0,0.0,checked
16,session_result,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
17,session_result,key_duplicate,NaN,NaN,before,"session_key,driver_number",0.0,0.0,0.0,checked
18,starting_grid,full_row_duplicate,0.0,0.0,before,NaN,NaN,NaN,NaN,NaN
19,starting_grid,key_duplicate,NaN,NaN,before,"session_key,driver_number",0.0,0.0,0.0,skipped_missing_columns
20,meetings,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
21,meetings,key_duplicate,NaN,NaN,after,meeting_key,0.0,0.0,0.0,checked
22,sessions,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
23,sessions,key_duplicate,NaN,NaN,after,session_key,0.0,0.0,0.0,checked
24,drivers,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
25,drivers,key_duplicate,NaN,NaN,after,"session_key,driver_number",0.0,0.0,0.0,checked
26,laps,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
27,laps,key_duplicate,NaN,NaN,after,"session_key,driver_number,lap_number",0.0,0.0,0.0,checked
28,pit,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
29,pit,key_duplicate,NaN,NaN,after,"session_key,driver_number,lap_number",0.0,0.0,0.0,checked
30,weather,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
31,weather,key_duplicate,NaN,NaN,after,"session_key,date",0.0,0.0,0.0,checked
32,position,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
33,position,key_duplicate,NaN,NaN,after,"session_key,driver_number,date",0.0,0.0,0.0,checked
34,race_control,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
35,race_control,key_duplicate,NaN,NaN,after,"session_key,date,message",0.0,0.0,0.0,checked
36,session_result,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
37,session_result,key_duplicate,NaN,NaN,after,"session_key,driver_number",0.0,0.0,0.0,checked
38,starting_grid,full_row_duplicate,0.0,0.0,after,NaN,NaN,NaN,NaN,NaN
39,starting_grid,key_duplicate,NaN,NaN,after,"session_key,driver_number",0.0,0.0,0.0,skipped_missing_columns

,child_table,parent_table,key_columns,child_rows,unmatched_rows,unmatched_pct,status,stage
0,drivers,sessions,session_key,2,0,0.0,checked,before
1,laps,sessions,session_key,2,0,0.0,checked,before
2,pit,sessions,session_key,2,0,0.0,checked,before
3,weather,sessions,session_key,2,0,0.0,checked,before
4,position,sessions,session_key,2,0,0.0,checked,before
5,race_control,sessions,session_key,2,0,0.0,checked,before
6,session_result,sessions,session_key,2,0,0.0,checked,before
7,starting_grid,sessions,session_key,0,0,0.0,skipped_empty_child,before
8,laps,drivers,"session_key,driver_number",40,0,0.0,checked,before
9,pit,drivers,"session_key,driver_number",38,0,0.0,checked,before
10,position,drivers,"session_key,driver_number",40,0,0.0,checked,before
11,session_result,drivers,"session_key,driver_number",40,0,0.0,checked,before
12,starting_grid,drivers,"session_key,driver_number",0,0,0.0,skipped_empty_child,before
13,drivers,sessions,session_key,2,0,0.0,checked,after
14,laps,sessions,session_key,2,0,0.0,checked,after
15,pit,sessions,session_key,2,0,0.0,checked,after
16,weather,sessions,session_key,2,0,0.0,checked,after
17,position,sessions,session_key,2,0,0.0,checked,after
18,race_control,sessions,session_key,2,0,0.0,checked,after
19,session_result,sessions,session_key,2,0,0.0,checked,after
20,starting_grid,sessions,session_key,0,0,0.0,skipped_empty_child,after
21,laps,drivers,"session_key,driver_number",40,0,0.0,checked,after
22,pit,drivers,"session_key,driver_number",38,0,0.0,checked,after
23,position,drivers,"session_key,driver_number",40,0,0.0,checked,after
24,session_result,drivers,"session_key,driver_number",40,0,0.0,checked,after
25,starting_grid,drivers,"session_key,driver_number",0,0,0.0,skipped_empty_child,after

Empty DataFrame
Columns: [table_name, reason, rule_id, rejected_count]
Index: []